import { Article } from '@prisma/client';

// password: password
export const articleList: Array<Omit<Article, 'id'>> = [
  {
    slug: 'mastering-react-hooks',
    title: 'Mastering React Hooks',
    description: "A deep dive into React's powerful hooks.",
    body: "## Introduction\nReact hooks revolutionized state management. Let's explore how.\n\n### useState\nThis hook allows managing local component state.\n```js\nconst [count, setCount] = useState(0);\n```\n### useEffect\nUsed for side effects like fetching data.\n```js\nuseEffect(() => {\n  console.log('Component mounted');\n}, []);\n```",
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 2,
    authorId: 1,
  },
  {
    slug: 'cyberpunk-design-trends',
    title: 'Cyberpunk Design Trends',
    description: 'A look at neon aesthetics and digital futurism.',
    body: '## Cyberpunk UI\nNeon colors, glitch effects, and futuristic fonts define cyberpunk UI design.\n\n### Inspiration\n- **Blade Runner 2049**\n- **Ghost in the Shell**\n\n### CSS Tricks\n```css\nbody {\n  background-color: #000;\n  color: #0ff;\n  text-shadow: 0 0 5px #0ff;\n}\n```',
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 2,
    authorId: 2,
  },
  {
    slug: 'introduction-to-quantum-computing',
    title: 'Introduction to Quantum Computing',
    description: 'Basics of quantum computing for developers.',
    body: '## What is Quantum Computing?\nQuantum computers leverage **qubits** instead of classical bits.\n\n### Key Concepts\n- **Superposition**: A qubit can be `0`, `1`, or both.\n- **Entanglement**: Two qubits can be linked regardless of distance.\n\n### Code Example\n```python\nfrom qiskit import QuantumCircuit\nqc = QuantumCircuit(2)\nqc.h(0)\nqc.cx(0, 1)\nqc.measure_all()\n```',
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 1,
    authorId: 3,
  },
  {
    slug: 'how-to-debug-like-a-pro',
    title: 'How to Debug Like a Pro',
    description: 'Techniques to find and fix bugs efficiently.',
    body: '## Debugging Strategies\nDebugging is a skill every developer must master.\n\n### Tools\n- **Chrome DevTools**\n- **VS Code Debugger**\n\n### Common Bugs\n```js\nconsole.log(variable); // ReferenceError: variable is not defined\n```\nSolution: Check if the variable is declared before use.',
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 1,
    authorId: 4,
  },
  {
    slug: 'ai-revolution-in-software-development',
    title: 'AI Revolution in Software Development',
    description: 'How AI is reshaping the future of coding.',
    body: '## AI in Development\nAI is automating many aspects of software development.\n\n### Use Cases\n- **Code Generation**: GitHub Copilot, ChatGPT\n- **Testing**: AI-powered testing tools\n\n### The Future\nWill AI replace developers? Likely not, but it will change how we code.',
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 3,
    authorId: 5,
  },
  {
    slug: 'why-crypto-matters-in-2025',
    title: 'Why Crypto Matters in 2025',
    description: 'The evolving role of cryptocurrency in finance.',
    body: "## Crypto in 2025\nCryptocurrency is no longer just speculation; it's an economic force.\n\n### Key Trends\n- **DeFi Growth**\n- **NFT Expansion**\n- **Regulatory Changes**\n\n### Is It Too Late to Invest?\nNo! But research projects thoroughly before investing.",
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 3,
    authorId: 6,
  },
  {
    slug: 'how-hackers-think',
    title: 'How Hackers Think',
    description: 'Understanding the mindset of ethical hackers.',
    body: '## The Hacker Mindset\nHackers look for vulnerabilities others ignore.\n\n### Common Attacks\n- **SQL Injection**\n- **XSS (Cross-Site Scripting)**\n\n### Ethical Hacking\nTry **Capture The Flag (CTF)** challenges to learn security.',
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 2,
    authorId: 7,
  },
  {
    slug: 'mechanical-engineering-meets-coding',
    title: 'Mechanical Engineering Meets Coding',
    description: 'How programming enhances mechanical design.',
    body: '## Coding for Engineers\nEngineers use code for simulations and automation.\n\n### Languages Used\n- **Python (for simulations)**\n- **MATLAB (for calculations)**\n- **C++ (for robotics)**',
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 2,
    authorId: 8,
  },
  {
    slug: 'coding-for-space-exploration',
    title: 'Coding for Space Exploration',
    description: 'How software helps us explore the universe.',
    body: "## Space and Code\nSpace agencies rely on software for calculations and control.\n\n### Famous Space Code\n- **Apollo 11 Guidance Computer**\n- **Mars Rover Autopilot**\n\n### Example\n```python\nimport numpy as np\nvelocity = np.sqrt(2 * 9.8 * 100)\nprint(f'Landing speed: {velocity} m/s')\n```",
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 3,
    authorId: 9,
  },
  {
    slug: 'javascript-tricks-for-wizards',
    title: 'JavaScript Tricks for Wizards',
    description: 'Advanced JavaScript magic for developers.',
    body: "## Advanced JS\nJavaScript is full of hidden tricks.\n\n### Example\n```js\nconsole.log(+'42' === 42); // true\nconsole.log([] + []); // ''\n```\n### Performance Hacks\nUse **memoization** to speed up function calls.",
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 3,
    authorId: 10,
  },
  {
    slug: 'best-practices-for-responsive-design',
    title: 'Best Practices for Responsive Design',
    description: 'How to make your websites look great on any device.',
    body: '## Responsive Design Basics\nUsing **flexible layouts**, **media queries**, and **fluid grids**.\n\n### Example\n```css\n@media (max-width: 768px) {\n  body { font-size: 14px; }\n}\n```',
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 2,
    authorId: 1,
  },
  {
    slug: 'dark-mode-ui-design',
    title: 'Dark Mode UI Design',
    description: 'Why dark mode is essential and how to implement it.',
    body: '## Dark Mode in CSS\n```css\nbody {\n  background-color: #121212;\n  color: #fff;\n}\n```',
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 2,
    authorId: 2,
  },
  {
    slug: 'understanding-async-await',
    title: 'Understanding Async/Await',
    description: 'Make JavaScript async functions easy to read and write.',
    body: "## Using Async/Await\n```js\nasync function fetchData() {\n  let response = await fetch('https://api.example.com/data');\n  let data = await response.json();\n  console.log(data);\n}\nfetchData();\n```",
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 3,
    authorId: 3,
  },
  {
    slug: 'effective-code-reviews',
    title: 'Effective Code Reviews',
    description: 'How to review code like a pro.',
    body: '## Code Review Tips\n- Look for readability\n- Ensure good variable names\n- Catch performance issues',
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 3,
    authorId: 4,
  },
  {
    slug: 'future-of-machine-learning',
    title: 'Future of Machine Learning',
    description: 'Where AI and ML are heading.',
    body: '## ML Trends\n- **Explainable AI**\n- **Automated ML (AutoML)**\n- **Edge AI**',
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 2,
    authorId: 5,
  },
  {
    slug: 'how-blockchain-works',
    title: 'How Blockchain Works',
    description: 'The technology behind cryptocurrencies and beyond.',
    body: "## What is Blockchain?\nA **decentralized**, **immutable** ledger.\n\n### Example\n```json\n{\n  'block': 1,\n  'previous_hash': '0000abc123',\n  'transactions': [...]\n}\n```",
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 2,
    authorId: 6,
  },
  {
    slug: 'how-to-harden-your-web-app',
    title: 'How to Harden Your Web App',
    description: 'Essential security practices for developers.',
    body: '## Security Tips\n- Use **HTTPS**\n- Sanitize **user inputs**\n- Implement **CORS correctly**',
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 2,
    authorId: 7,
  },
  {
    slug: 'why-learn-rust',
    title: 'Why Learn Rust?',
    description: 'A guide to Rust and its advantages.',
    body: '## Why Rust?\nRust is **safe**, **fast**, and **concurrent**.\n\n### Example\n```rust\nfn main() {\n  println!("Hello, Rust!");\n}\n```',
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 3,
    authorId: 8,
  },
  {
    slug: 'how-nasa-uses-python',
    title: 'How NASA Uses Python',
    description: 'Python in space exploration.',
    body: '## NASA and Python\nNASA uses Python for:\n- **Data analysis**\n- **Machine learning**\n- **Simulations**',
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 2,
    authorId: 9,
  },
  {
    slug: 'top-javascript-frameworks-2025',
    title: 'Top JavaScript Frameworks in 2025',
    description: 'Which JS frameworks are dominating?',
    body: '## Top Frameworks\n- **React**\n- **Vue**\n- **Svelte**\n- **SolidJS**',
    createdAt: new Date(),
    updatedAt: new Date(),
    favoritesCount: 3,
    authorId: 10,
  },
];
