import { ArticleToTag } from '@prisma/client';
export const articleToTag: Array<ArticleToTag> = [
  { id: 1, tagId: 1, articleId: 1 },
  { id: 2, tagId: 2, articleId: 1 },
  { id: 3, tagId: 3, articleId: 2 },
  { id: 4, tagId: 4, articleId: 2 },
  { id: 5, tagId: 5, articleId: 3 },
  { id: 6, tagId: 6, articleId: 3 },
  { id: 7, tagId: 7, articleId: 4 },
  { id: 8, tagId: 8, articleId: 4 },
  { id: 9, tagId: 1, articleId: 5 },
  { id: 10, tagId: 3, articleId: 5 },
  { id: 11, tagId: 2, articleId: 6 },
  { id: 12, tagId: 4, articleId: 6 },
  { id: 13, tagId: 5, articleId: 7 },
  { id: 14, tagId: 6, articleId: 7 },
  { id: 15, tagId: 7, articleId: 8 },
  { id: 16, tagId: 8, articleId: 8 },
  { id: 17, tagId: 1, articleId: 9 },
  { id: 18, tagId: 3, articleId: 9 },
  { id: 19, tagId: 2, articleId: 10 },
  { id: 20, tagId: 4, articleId: 10 },
  { id: 21, tagId: 5, articleId: 11 },
];
