import { UserToUser } from '@prisma/client';

export const userToUser: Array<UserToUser> = [
  { id: 1, followerId: 1, followingId: 2 },
  { id: 2, followerId: 1, followingId: 3 },
  { id: 3, followerId: 1, followingId: 4 },
  { id: 4, followerId: 2, followingId: 1 },
  { id: 5, followerId: 2, followingId: 3 },
  { id: 6, followerId: 2, followingId: 5 },
  { id: 7, followerId: 3, followingId: 1 },
  { id: 8, followerId: 3, followingId: 2 },
  { id: 9, followerId: 3, followingId: 4 },
  { id: 10, followerId: 3, followingId: 5 },
  { id: 11, followerId: 4, followingId: 1 },
  { id: 12, followerId: 4, followingId: 2 },
  { id: 13, followerId: 4, followingId: 3 },
  { id: 14, followerId: 4, followingId: 6 },
  { id: 15, followerId: 5, followingId: 2 },
  { id: 16, followerId: 5, followingId: 3 },
  { id: 17, followerId: 5, followingId: 4 },
  { id: 18, followerId: 5, followingId: 7 },
  { id: 19, followerId: 6, followingId: 4 },
  { id: 20, followerId: 6, followingId: 5 },
  { id: 21, followerId: 6, followingId: 7 },
  { id: 22, followerId: 6, followingId: 8 },
  { id: 23, followerId: 7, followingId: 5 },
  { id: 24, followerId: 7, followingId: 6 },
  { id: 25, followerId: 7, followingId: 8 },
  { id: 26, followerId: 7, followingId: 9 },
  { id: 27, followerId: 8, followingId: 6 },
  { id: 28, followerId: 8, followingId: 7 },
  { id: 29, followerId: 8, followingId: 9 },
  { id: 30, followerId: 8, followingId: 10 },
  { id: 31, followerId: 9, followingId: 7 },
  { id: 32, followerId: 9, followingId: 8 },
  { id: 33, followerId: 9, followingId: 10 },
  { id: 34, followerId: 9, followingId: 1 },
  { id: 35, followerId: 10, followingId: 8 },
  { id: 36, followerId: 10, followingId: 9 },
  { id: 37, followerId: 10, followingId: 1 },
  { id: 38, followerId: 10, followingId: 2 },
];
